# Generated by Django 5.0.2 on 2024-03-04 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('address_line_1', models.CharField(max_length=150)),
                ('address_line_2', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.CharField(default='India', max_length=150)),
                ('state', models.CharField(default='Madhya Pradesh', max_length=150)),
                ('city', models.CharField(default='Burhanpur', max_length=150)),
                ('zip_code', models.CharField(default='450331', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('cr_at', models.DateTimeField(auto_now_add=True)),
                ('up_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('making_charges', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('cr_at', models.DateTimeField(auto_now_add=True)),
                ('up_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('cr_at', models.DateTimeField(auto_now_add=True)),
                ('up_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.customer')),
                ('products', models.ManyToManyField(to='invoice.product')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
