# Generated by Django 5.0.2 on 2024-03-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.AddField(
            model_name='invoice',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='invoice',
            name='city',
            field=models.CharField(default='Burhanpur', max_length=150),
        ),
        migrations.AddField(
            model_name='invoice',
            name='country',
            field=models.CharField(default='India', max_length=150),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mobile',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='invoice',
            name='state',
            field=models.CharField(default='Madhya Pradesh', max_length=150),
        ),
        migrations.AddField(
            model_name='invoice',
            name='zip_code',
            field=models.CharField(default='450331', max_length=7),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
