# Generated by Django 5.0.2 on 2024-03-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tax_rate',
        ),
    ]
