# Generated by Django 5.0.2 on 2024-07-06 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_advancepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancepayment',
            name='products',
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice'),
        ),
    ]
